USE [RandomCode]
GO
CREATE TABLE [dbo].[Batch]
(
	[ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[BatchName] VARCHAR(50) NOT NULL,
	[BatchSize] int NOT NULL,
	[PromotionType] VARCHAR(50) NOT NULL,
	[DateActive] DATETIME NOT NULL,
	[DateExpires] DATETIME NOT NULL
)